version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Api/Movies.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabaseName;User Id=sa;Password=Admin1234;

  frontend:
    build:
      context: .
      dockerfile: ./UI/Dockerfile
    ports:
      - "3000:3000"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: true
      MSSQL_SA_PASSWORD: "Admin1234"
    ports:
      - "1433:1433"